[package]
name = "emu"
version = "0.1.0"
authors = ["calebwin <calebhwin@gmail.com>"]
edition = "2018"

[dependencies]
quote = "0.6.11"
syn = { version = "0.15.29", features = ["full", "visit", "extra-traits"] }

[lib]
proc-macro = true